import logo from './logo.svg';
import './App.css';

import {
    after,
    assign,
    at,
    bind,
    bindAll,
    bindKey,
    chain,
    clone,
    cloneDeep,
    compact,
    constant,
    countBy,
    create,
    curry,
    debounce,
    defaults,
    defer,
    delay,
    difference,
    drop,
    each,
    eachRight,
    escape,
    every,
    extend,
    filter,
    find,
    findIndex,
    findKey,
    findLast,
    findLastIndex,
    findLastKey,
    first,
    flatten,
    forEach,
    forEachRight,
    forIn,
    forInRight,
    forOwn,
    forOwnRight,
    functions,
    groupBy,
    has,
    head,
    identity,
    indexOf,
    initial,
    intersection,
    invert,
    invoke,
    isArguments,
    isArray,
    isBoolean,
    isDate,
    isElement,
    isEmpty,
    isEqual,
    isFinite,
    isFunction,
    isNaN,
    isNull,
    isNumber,
    isObject,
    isPlainObject,
    isRegExp,
    isString,
    isUndefined,
} from "lodash";

const _ = {
    after,
    assign,
    at,
    bind,
    bindAll,
    bindKey,
    chain,
    clone,
    cloneDeep,
    compact,
    constant,
    countBy,
    create,
    curry,
    debounce,
    defaults,
    defer,
    delay,
    difference,
    drop,
    each,
    eachRight,
    escape,
    every,
    extend,
    filter,
    find,
    findIndex,
    findKey,
    findLast,
    findLastIndex,
    findLastKey,
    first,
    flatten,
    forEach,
    forEachRight,
    forIn,
    forInRight,
    forOwn,
    forOwnRight,
    functions,
    groupBy,
    has,
    head,
    identity,
    indexOf,
    initial,
    intersection,
    invert,
    invoke,
    isArguments,
    isArray,
    isBoolean,
    isDate,
    isElement,
    isEmpty,
    isEqual,
    isFinite,
    isFunction,
    isNaN,
    isNull,
    isNumber,
    isObject,
    isPlainObject,
    isRegExp,
    isString,
    isUndefined,
}

function App() {
    return (<div className="App">
        <header className="App-header">
            <img src={logo} className="App-logo" alt="logo"/>
            <p>
                Edit <code>src/App.js</code> and save to reload.
            </p>
            <a
                className="App-link"
                href="https://reactjs.org"
                target="_blank"
                rel="noopener noreferrer"
            >
                Learn React
            </a>
        </header>
    </div>);
}

export default App;
